name: test

on:
  push:
  pull_request:
    types: [opened, reopened, review_requested, synchronize]

jobs:
  run-tests:
    strategy:
      matrix:
        os: ["ubuntu:22.04"]
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.os }}
    steps:
        
      - name: Install dependencies on Ubuntu 22.04
        if: matrix.os == 'ubuntu:22.04'
        run: |
          apt update -y
          apt install -y default-jdk build-essential bison flex gettext texinfo automake autoconf libgmp3-dev

      - name: Checkout opensource COBOL
        uses: actions/checkout@v3
      
      - name: Install opensource COBOL
        run: |
          ./configure --prefix=/usr/
          make
          make install

      - name: Run sample.cbl
        run: |
          cd sample/
          cobc sample.cbl
          cobcrun sample